services:
  - type: web
    name: pathtotech-ml
    env: python
    pythonVersion: 3.11
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATASET_PATH
        value: dataset/employability.xlsx
